### ISSUE TITLE
Possible memory consumption spikes

### ISSUE THREAD

**Issue by voneiden** [SodiumEyes/KerbalLiveFeed#3]
With the 0.0.7 the server has crashed now bout 4 times. The crashes seem to be timed random and aren't at least related to the peak stress of the server (ie. it worked just fine when we had 10 players there).

Now the issue might as well related to the server computer.. it has under normal operating conditions 262MB of free memory (of which physical only 22MB..which could of course also be the problem). I've not noticed the memory usage to fluctuate under these normal operating conditions which leads me to presume it's a special condition (either triggered by the system or KLF).

One thing I'd like to see in the server console are timestamps, so it would be easier to determine if things such as join events are related to crashes.

One thing I noticed is that it's now the 2nd time the server crashes after there are messages about this "new user" -person joining/disconnecting. Coincidence?

Client #4 AlternNocturn has disconnected.  
Accepted client. Handshaking...
AlternNocturn has joined the server using client version 0.0.7
[AlternNocturn] Sorry, apparently my CTRL button got stuck
[AlternNocturn] Turn out CTRL+C closes out the command prompt
Client #2 SodiumEyes has disconnected.
[tetryds] yep
[tetryds] ctrlc closes it i tried too
[AlternNocturn] I like how now we're both doing the exact same thing
Client #1 new user has disconnected.
Client #0 efisher has disconnected.
Accepted client. Handshaking...
Accepted client. Handshaking...
Accepted client. Handshaking...
Accepted client. Handshaking...
Accepted client. Handshaking...
Accepted client. Handshaking...
Client #1 new user has disconnected.
tetryds has joined the server using client version 0.0.7
[AlternNocturn] Finally!
Unhandled Exception: OutOfMemoryException  
[ERROR] FATAL UNHANDLED EXCEPTION: System.OutOfMemoryException: Out of memory
  at KLFServer.ServerClient.listenForMessages () [0x00000] in <filename unknown>
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by voneiden** [comment]
Out of curiosity, was there actually something causing this? Because I haven't had this issue repeat with the never versions at least so far.

**Comment by SodiumEyes** [comment]
I believe it was due to clients that did not handshake building up in the client list, though it should not have caused a crash if the server's memory is sufficient for its max client count.
