### ISSUE TITLE
0.1.0 Server: Console colors went wild

### ISSUE THREAD

**Issue by voneiden** [SodiumEyes/KerbalLiveFeed#6]
![colorbug](https://f.cloud.github.com/assets/437576/188720/36ed11d8-7e08-11e2-8be1-a98671c757e8.png)

I'm guessing there was an exception in  `public static void stampedConsoleWriteLine` (hence the double [), which in turn set the `default_color` as timestamp color.

As can be seen in the middle shot (that's from putty/kitty running on windows), timestamp DarkGrey appears as black. In the bottom shot (which is from xterm running on linux), it's.. kinda the opposite.  

Perhaps using http://msdn.microsoft.com/en-us/library/system.console.resetcolor.aspx helps to fix and simplify the situation?

Still no clue though why DarkGray would appear as black on putty/kitty. I haven't checked any other colors yet if they would work better.

**Comment by SodiumEyes** [comment]
Probably fixed?

**Comment by voneiden** [comment]
I think so. Has not occurred again in 0.1.3
